EAM/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls',namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login,logout,logout_then_login
from django.contrib.auth.views import password_change,password_change_done
from .views import UserPostView,PostCreateView,UserPostEditView,UserPostDeleteView
from .views import DepartmentListView,DepartmentCreateView,DepartmentDeleteView,DepartmentEditView
from .views import UserListView,UserDetailView,UserEditView

from .views import dashboard
app_name='account'

urlpatterns = [
    url(r'^login/$',login,name='login'),
    url(r'^logout/$',logout,name='logout'),
    url(r'^logout-then-login/$',logout_then_login,name='logout-then-login'),
    url(r'^$',dashboard,name='dashboard'),
    url(r'^passwd-change/$',password_change,{'post_change_redirect':'account:passwd_done'},name='passwd_change'),
    url(r'passwd-change/done/$',password_change_done,name='passwd_done'),
    url(r'^post/$',UserPostView.as_view(),name='post_list'),
    url(r'^post/delete/$',UserPostDeleteView.as_view(),name='post_delete'),
    url(r'^post/create/$',PostCreateView.as_view(),name='post_create'),
    url(r'^post/(?P<pk>\d+)/edit/$',UserPostEditView.as_view(),name='post_edit'),
    url(r'^department/$',DepartmentListView.as_view(),name="department_list"),
    url(r'^department/create/$',DepartmentCreateView.as_view(),name='department_create'),
    url(r'^department/delete/$',DepartmentDeleteView.as_view(),name='department_delete'),
    url(r'department/(?P<pk>\d+)/edit/$',DepartmentEditView.as_view(),name='department_edit'),
    url(r'^user/$',UserListView.as_view(),name='user_list'),
    url(r'^user/(?P<pk>\d+)/$',UserDetailView.as_view(),name="user_detail"),
    url(r'^user/(?P<pk>\d+)/edit/$',UserEditView.as_view(),name="user_edit"),
    #url(r'^$',DashboardView().index,name='dashboard'),
]

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from .fields import OrderField
from django.db.models.signals import post_save


# Create your models here.
class UserPost(models.Model):

    name = models.CharField('职位',max_length=150)
    active= models.BooleanField(default=True,verbose_name='是否启用')
    order = OrderField(blank=True,verbose_name='排序')

    class Meta:
        ordering = ['order']
        verbose_name = '岗位'
        verbose_name_plural = '岗位管理'

    def __str__(self):
        return self.name

class Department(models.Model):

    name = models.CharField('部门名称',max_length=200)
    active = models.BooleanField(default=True,verbose_name='是否启用')
    order = OrderField(blank=True,verbose_name='排序')

    class Meta:
        ordering = ['order']
        verbose_name = '部门'
        verbose_name_plural = '部门管理'

    def __str__(self):
        return self.name

class Profile(models.Model):

    GENDER_CHOICES=(
        ('M','男'),('F','女'),
    )
    JOB_CHOICES=(
        ('ON','在职'),('OUT','离职'),
    )
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    gender = models.CharField('性别',max_length=10,choices=GENDER_CHOICES)
    phone = models.PositiveIntegerField('联系方式',blank=True)
    date_of_birth = models.DateField('出生日期',blank=True,null=True)
    post = models.ForeignKey(UserPost,related_name='post_Profile',on_delete=models.CASCADE,verbose_name='岗位')
    department = models.ForeignKey(Department,related_name='Profiles',on_delete=models.CASCADE,verbose_name='部门')
    status = models.CharField('人员状态',max_length=10,choices=JOB_CHOICES,help_text="员工是否在职")

    def __str__(self):
        return "{}详细信息".format(self.user.username)

def create_user_profile(sender,instance,created,**kwargs):
    if created:
        profile,created = Profile.objects.get_or_create(user=instance)

post_save.connect(create_user_profile,sender=User)

account/forms.py
from django import forms
from .models import Profile

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=('gender','phone','date_of_birth','post','department','status')

account/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views.generic import ListView,View,CreateView,DetailView,UpdateView,DeleteView
from django.views.generic.base import TemplateResponseMixin
from .models import UserPost,Department,Profile
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import ProfileEditForm
import re
# Create your views here.
@login_required
def dashboard(request):
    #AdminSite.index_template='account/dashboard.html'
    #return AdminSite().index(request)

    return render(request,'account/dashboard.html',{'section':'index'})

class UserPostMixin(LoginRequiredMixin):
    model = UserPost
    extra_context = {'section': 'post'}
    success_url = reverse_lazy("account:post_list")

class UserPostView(UserPostMixin,ListView):
    template_name = 'account/post_list.html'
    paginate_by = 10
    paginate_orphans = 0

class UserPostDeleteView(PermissionRequiredMixin,View):
    permission_required = 'UserPost.delete_userpost'
    def post(self,request):
        post_name = request.POST.getlist('postname[]')
        post_ids = request.POST.getlist('post_id[]')
        post_ids=','.join(post_ids)
        try:

            UserPost.objects.extra(where=['id IN ( '+post_ids+')']).delete()
            msg = "已成功删除岗位 {}".format(' '.join(post_name))
            messages.success(request, msg)
            return  JsonResponse({'status':'ok'})
        except UserPost.DoesNotExist:
            msg = "删除失败 {}".format(post_name)
            messages.warning(request, msg)
            return JsonResponse({'status':'ko'})

class UserPostEditView(PermissionRequiredMixin,UserPostMixin,UpdateView):
    fields = ['name','active','order']
    template_name = "account/post_form.html"
    permission_required = 'UserPost.change_userpost'

class PostCreateView(PermissionRequiredMixin,UserPostMixin,CreateView):
    permission_required = 'UserPost.add_userpost'
    fields = ['name','active','order']
    template_name = "account/post_form.html"
    def post(self, request, *args, **kwargs):
        post_name = request.POST.get('name')
        if UserPost.objects.filter(name=post_name):
            msg = "岗位{}已经存在 ".format(post_name)
            messages.info(request, msg)
            return redirect(reverse_lazy("account:post_create"))
        else:
            if "_save" not in request.POST:
                self.success_url = reverse_lazy("account:post_create")
            msg = "成功添加岗位 {}".format(post_name)
            messages.success(request,msg)
            return super(PostCreateView,self).post(request, *args, **kwargs)

class DepartmentMixin(LoginRequiredMixin):
    model = Department
    extra_context = {'section': 'department'}
    success_url = reverse_lazy("account:department_list")

class DepartmentListView(DepartmentMixin,ListView):
    template_name = "account/department_list.html"
    paginate_by = 10
    paginate_orphans = 0

class DepartmentCreateView(PermissionRequiredMixin,DepartmentMixin,CreateView):
    template_name = "account/department_form.html"
    fields = ['name','active','order']
    permission_required = 'Department.add_department'

    def post(self, request, *args, **kwargs):
        de_name = request.POST.get('name')
        if Department.objects.filter(name=de_name):
            msg = "部门 {} 已经存在 ".format(de_name)
            messages.info(request, msg)
            return redirect(reverse_lazy("account:department_create"))
        else:
            if "_save" not in request.POST:
                self.success_url = reverse_lazy("account:department_create")
            msg = "成功添加部门 {}".format(de_name)
            messages.success(request, msg)
            return super(DepartmentCreateView, self).post(request, *args, **kwargs)

class DepartmentDeleteView(PermissionRequiredMixin,DepartmentMixin,DeleteView):
    permission_required = 'Department.delete_department'
    def post(self, request, *args, **kwargs):
        name = request.POST.getlist('checkbox')
        del_name=','.join(name)
        try:
            Department.objects.extra(where=['id IN ('+ del_name +')']).delete()
            msg = "已成功删除岗位{}".format(del_name)
            messages.success(request, msg)
        except UserPost.DoesNotExist:
            msg = "删除失败 {}".format(del_name)
            messages.warning(request, msg)
        return redirect(self.success_url)

class DepartmentEditView(PermissionRequiredMixin,DepartmentMixin,UpdateView):
    template_name = "account/department_form.html"
    permission_required = 'Department.change_department'
    fields = ['name', 'active', 'order']

class Usermixin(LoginRequiredMixin):
    model = User
    extra_context = {'section': 'user'}
    success_url = reverse_lazy("account:user_list")
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        if self.request.method == "POST":
            p_form = ProfileEditForm(self.request.Post)
        else:
            p_form = ProfileEditForm(instance=self.request.user.profile)
        context['p_form'] = p_form
        return context
    def 

class UserListView(Usermixin,ListView):
    template_name = "account/user_list.html"

class UserDetailView(Usermixin,DetailView):
    template_name = "account/user_detail.html"


class UserEditView(PermissionRequiredMixin,Usermixin,UpdateView):
    template_name = "account/user_form.html"
    permission_required = 'user.change_user'
    fields = ['username','last_name','first_name','email','is_active','is_staff']

account/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="zhousc">

    <title>{% block title %}资产管理系统{% endblock %}|Zhousc</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{%  static "css/ie10-viewport-bug-workaround.css"%}" rel="stylesheet">

{% block link %}
{% endblock %}
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static "js/ie-emulation-modes-warning.js" %}"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
  {% block content %}
  {% endblock %}
  <script src="{% static "js/jquery.min.js"%}"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static "js/bootstrap.js" %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static "js/holder.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
</body></html>

account/templates/main.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ request.user }}|资产管理{% endblock %}
{% block link %}
    <!-- Custom styles for this template -->
    <link href="{% static "css/dashboard.css"%}" rel="stylesheet">
{% endblock %}
{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
          {% if request.user.is_authenticated %}
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">切换导航</span>
              <span class="icon-bar">ZHOUSC</span>
          </button>
          <a class="navbar-brand" href="{% url "account:dashboard" %}#">资产管理</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url "account:user_detail" request.user.id %}" class="glyphicon glyphicon-user"> 欢迎{{ request.user }}</a></li>
            <li><a href="/admin/ ">配置</a></li>
            <li><a href="{% url "account:passwd_change" %}">密码更改</a></li>
            <li><a href="{% url "account:logout" %}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
          {% endif %}
      </div>
    </nav>

    <div class="container-fluid" >
    {% if request.user.is_authenticated %}
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar" style="width: 18%">
          <ul class="nav nav-sidebar">

            <li {% if section == 'index' %}class="active"{% endif %}><a href="{% url "account:dashboard" %}">个人首页<span class="sr-only">(current)</span></a></li>
            <li{% if section == 'department'%} class="active"{% endif %}><a href="{% url "account:department_list" %}">部门管理</a></li>
            <li{% if section == 'post' %} class="active"{% endif %}><a href="{%  url "account:post_list" %}">岗位管理</a></li>
            <li{% if section == 'user' %} class="active"{% endif %}><a href="{%  url "account:user_list" %}">人员管理</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="https://v3.bootcss.com/examples/dashboard/">Nav item</a></li>
            <li><a href="https://v3.bootcss.com/examples/dashboard/">Nav item again</a></li>
            <li><a href="https://v3.bootcss.com/examples/dashboard/">One more nav</a></li>
            <li><a href="https://v3.bootcss.com/examples/dashboard/">Another nav item</a></li>
            <li><a href="https://v3.bootcss.com/examples/dashboard/">More navigation</a></li>
          </ul>
 {% endif %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="padding-left: 50px">
        {% block message %}
            {% if messages %}
                {% for message in messages %}
           <p class="alert alert-{{ message.tags}}">{{ message }}</p>
                {% endfor %}
            {% endif %}
         {% endblock %}
            {% block main %}
            {% endblock %}
{% endblock %}

account/templates/pages.html
{% if page_obj %}

    <ul class="pagination pagination-lg">
<li{% if page_obj.number == 1 %} class="disabled"{% endif %}><a href="#">&laquo;</a></li>{{ i }}
    {% for i in page_obj.paginator.page_range %}
    <li><a href="?page={{ i }}">{{ i }}</a></li>{% endfor %}
    <li{% if page_obj.number == paginator.num_pages %} class="disabled"{% endif %}><a href="#">&raquo;</a></li>
{% endif %}
</ul>